-- Generated by hypr/scripts/theme.sh — edits here are overwritten.
-- Active theme: Catppuccin Mocha
return {
    crust = "11111b", mantle = "181825", base = "1e1e2e",
    surface0 = "313244", surface1 = "45475a", overlay = "6c7086",
    subtext = "a6adc8", text = "cdd6f4", rosewater = "f5e0dc",
    red = "f38ba8", peach = "fab387", yellow = "f9e2af",
    green = "a6e3a1", teal = "94e2d5", sapphire = "74c7ec",
    blue = "89b4fa", lavender = "b4befe", mauve = "cba6f7", pink = "f5c2e7",
}
