--------------------------------------------------------------------------------
--  Hyprland — main configuration
--
--  Hyprland 0.55 deprecated the hyprlang .conf format in favour of Lua, and
--  0.57 removes it. Hyprland looks for hyprland.lua in this directory (NOT
--  init.lua); the modules are plain Lua files in
--  this directory, loaded with require() (package.path already includes it).
--
--    monitors.lua   display layout          (generated by the installer)
--    gpu.lua        vendor GPU variables    (generated by the installer)
--    colors.lua     active palette          (generated by scripts/theme.sh)
--    env.lua        environment variables
--    theme.lua      gaps, borders, blur, animations
--    input.lua      keyboard, mouse, touchpad, gestures
--    keybinds.lua   every keyboard shortcut
--    rules.lua      per-window, per-layer and per-workspace rules
--    autostart.lua  programs started at login
--
--  Reference: https://wiki.hypr.land/Configuring/
--------------------------------------------------------------------------------

-- monitors.lua and gpu.lua are generated per machine by install.sh, so they do
-- not exist until it has run. Live media has never run it, and a hard require
-- there fails the whole config and drops Hyprland into emergency mode with no
-- binds. Hyprland's own defaults are correct in that case: displays are
-- auto-detected, and no vendor GPU variables are set.
--
-- Only a genuinely missing file is tolerated. An error *inside* one of these
-- modules is re-raised, because silently ignoring a broken generated file
-- would hide a real bug behind a working-looking desktop.
local function optional(name)
    local ok, err = pcall(require, name)
    if ok then return end
    if tostring(err):match("module '" .. name .. "' not found") then return end
    error(err, 0)
end

optional("monitors")
require("env")
optional("gpu")
require("theme")
require("input")
require("keybinds")
require("rules")
require("autostart")

hl.config({
    misc = {
        -- The Hyprland logo wallpaper and the "how to configure" banner.
        disable_hyprland_logo    = true,
        disable_splash_rendering = true,

        -- Do not switch focus just because an app asked for it.
        focus_on_activate = false,

        -- Adaptive sync: 0 off, 1 on, 2 fullscreen-only. 2 is the safe default,
        -- since some apps flicker with VRR always on.
        vrr = 2,

        -- Middle-click paste on a titlebar is more often an accident than intent.
        middle_click_paste = false,

        key_press_enables_dpms  = true,
        mouse_move_enables_dpms = true,
    },

    xwayland = {
        -- Let X11 apps render at native resolution instead of being upscaled
        -- and blurred. If one looks tiny, set this false and let Hyprland scale.
        force_zero_scaling = true,
    },

    render = {
        -- Hand the buffer straight to the display when one fullscreen window
        -- owns the screen. Meaningful latency win for games and video.
        direct_scanout = 1,
    },

    ecosystem = {
        no_update_news = true,
    },
})
