--------------------------------------------------------------------------------
--  Appearance — spacing, borders, blur, animations
--
--  Everything here is structure. The colours come from the active theme;
--  SUPER+SHIFT+T switches between them. colors.lua is generated by
--  hypr/scripts/theme.sh and returns a table of role -> six-digit hex.
--------------------------------------------------------------------------------

local c = require("colors")

-- hyprlang wrote colours as rgb(hex); the Lua API takes the same string form.
local function rgb(hex) return "rgb(" .. hex .. ")" end

hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 10,

        border_size = 2,

        col = {
            -- 45deg makes the gradient read as a light source.
            active_border   = { colors = { rgb(c.accent), rgb(c.blue) }, angle = 45 },
            inactive_border = rgb(c.surface0),
        },

        resize_on_border     = true,
        hover_icon_on_border = true,

        layout = "dwindle",

        -- Only for windows that explicitly ask; see rules.lua.
        allow_tearing = true,
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2.0,

        active_opacity   = 1.0,
        inactive_opacity = 0.96,

        shadow = {
            enabled      = true,
            range        = 20,
            render_power = 3,
            color        = "rgba(" .. c.crust .. "aa)",
            offset       = { 0, 4 },
        },

        blur = {
            enabled = true,
            size    = 6,
            passes  = 3,
            -- Only blur what is actually behind the window.
            new_optimizations  = true,
            ignore_opacity     = true,
            xray               = false,
            noise              = 0.012,
            contrast           = 1.0,
            brightness         = 0.85,
            popups             = true,
            popups_ignorealpha = 0.4,
        },
    },

    animations = { enabled = true },

    dwindle = {
        -- Keep a split's direction once chosen.
        preserve_split = true,
        smart_split    = false,
        smart_resizing = true,
        -- On an ultrawide, split side-by-side until windows get narrow.
        force_split    = 2,
    },

    master = {
        new_status     = "master",
        new_on_top     = false,
        mfact          = 0.5,
        orientation    = "left",
        smart_resizing = true,
    },

    -- Built in as of 0.56 — no plugin. An endless horizontal tape of columns;
    -- SUPER+T toggles it against dwindle at runtime.
    scrolling = {
        column_width           = 0.5,
        explicit_column_widths = "0.333, 0.5, 0.667, 1.0",
        direction              = "right",
        follow_focus           = true,
        follow_min_visible     = 0.4,
        wrap_focus             = true,
        wrap_swapcol           = true,
        fullscreen_on_one_column = true,
    },

    group = {
        col = {
            border_active   = { colors = { rgb(c.accent), rgb(c.blue) }, angle = 45 },
            border_inactive = rgb(c.surface0),
        },
        groupbar = {
            enabled     = true,
            font_family = "JetBrainsMono Nerd Font",
            font_size   = 11,
            height      = 16,
            gradients   = true,
            col = {
                active   = rgb(c.accent),
                inactive = rgb(c.surface0),
            },
            text_color = rgb(c.text),
        },
    },
})

-- Tuned to feel quick rather than showy: nothing runs longer than ~250ms.
hl.curve("easeOutQuint",   { type = "bezier", points = { { 0.23, 1 },    { 0.32, 1 }   } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 }   } })
hl.curve("linear",         { type = "bezier", points = { { 0, 0 },       { 1, 1 }      } })
hl.curve("almostLinear",   { type = "bezier", points = { { 0.5, 0.5 },   { 0.75, 1.0 } } })
hl.curve("quick",          { type = "bezier", points = { { 0.15, 0 },    { 0.1, 1 }    } })

hl.animation({ leaf = "global",           enabled = true, speed = 8,   bezier = "default" })
hl.animation({ leaf = "border",           enabled = true, speed = 5,   bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",          enabled = true, speed = 4,   bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn",        enabled = true, speed = 4,   bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut",       enabled = true, speed = 2,   bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",           enabled = true, speed = 2,   bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",          enabled = true, speed = 1.5, bezier = "almostLinear" })
hl.animation({ leaf = "fade",             enabled = true, speed = 3,   bezier = "quick" })
hl.animation({ leaf = "layers",           enabled = true, speed = 3,   bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",         enabled = true, speed = 3,   bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",        enabled = true, speed = 1.5, bezier = "linear",       style = "fade" })
hl.animation({ leaf = "workspaces",       enabled = true, speed = 2,   bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",     enabled = true, speed = 2,   bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut",    enabled = true, speed = 2,   bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 3,   bezier = "easeOutQuint", style = "slidevert" })
