"""Rendering config files, and writing them safely.

Every file this module produces is *generated*: starch-config rewrites it whole
and any hand edit to it is lost. That is stated in the header of each one, and
the previous contents are kept alongside as .bak, because a settings app that
silently eats a config someone spent an evening on is worse than no settings
app.

Files that are hand-written — input.lua, theme.lua, keybinds.lua — are never
touched here. Where a hand-written file needs overriding, we emit settings.lua
instead and let Hyprland's last-writer-wins settle it.
"""

import os
import shutil
from datetime import datetime
from pathlib import Path

BANNER = "Generated by starch-config"


def write(path: Path, text: str) -> None:
    """Replace `path` atomically, keeping one backup.

    Atomic because a half-written monitors.lua is a config error, and a config
    error on the display module is the one that leaves you with no way to see
    what went wrong.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        shutil.copy2(path, path.with_suffix(path.suffix + ".bak"))

    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text)
    os.replace(tmp, path)


def _header(what: str, extra: str = "") -> str:
    when = datetime.now().astimezone().strftime("%Y-%m-%d %H:%M")
    lines = [
        f"-- {BANNER} on {when}. Edits here are overwritten.",
        f"-- {what}",
    ]
    if extra:
        lines += ["--"] + [f"-- {line}" for line in extra.strip().splitlines()]
    return "\n".join(lines) + "\n\n"


def monitors_lua(entries) -> str:
    """`entries` is a list of dicts: output, mode, position, scale."""
    body = _header(
        "Display layout. Change it in starch-config, or with nwg-displays.",
        """
Scale must land on a whole pixel: RESOLUTION / SCALE has to be an integer in
both axes, and the scale itself a multiple of 1/120. Hyprland does not error
on a bad value, it silently snaps to the nearest legal one — which is why
starch-config only offers scales that are legal for the mode in question.
        """,
    )

    for e in entries:
        body += (
            'hl.monitor({{ output = "{output}", mode = "{mode}", '
            'position = "{position}", scale = {scale} }})\n'
        ).format(**e)

    fallback = entries[0]["scale"] if entries else 1
    body += (
        "\n-- Catch-all for a display plugged in later. If its resolution does not\n"
        "-- divide evenly by this scale Hyprland will snap to the nearest legal one;\n"
        "-- run starch-config again to give it a line of its own.\n"
        f'hl.monitor({{ output = "", mode = "preferred", position = "auto", scale = {fallback} }})\n'
    )
    return body


def scale_str(scale: float) -> str:
    """Hyprland wants enough digits that 4/3 does not read as 1.33."""
    text = f"{scale:.7f}".rstrip("0").rstrip(".")
    return text or "1"
