"""Rendering config files, and writing them safely.

Every file this module produces is *generated*: starch-config rewrites it whole
and any hand edit to it is lost. That is stated in the header of each one, and
the previous contents are kept alongside as .bak, because a settings app that
silently eats a config someone spent an evening on is worse than no settings
app.

Files that are hand-written — input.lua, theme.lua, keybinds.lua — are never
touched here. Where a hand-written file needs overriding, we emit settings.lua
instead and let Hyprland's last-writer-wins settle it.
"""

import os
import shutil
from datetime import datetime
from pathlib import Path

BANNER = "Generated by starch-config"


def write(path: Path, text: str) -> None:
    """Replace `path` atomically, keeping one backup.

    Atomic because a half-written monitors.lua is a config error, and a config
    error on the display module is the one that leaves you with no way to see
    what went wrong.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        shutil.copy2(path, path.with_suffix(path.suffix + ".bak"))

    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text)
    os.replace(tmp, path)


def _header(what: str, extra: str = "") -> str:
    when = datetime.now().astimezone().strftime("%Y-%m-%d %H:%M")
    lines = [
        f"-- {BANNER} on {when}. Edits here are overwritten.",
        f"-- {what}",
    ]
    if extra:
        lines += ["--"] + [f"-- {line}" for line in extra.strip().splitlines()]
    return "\n".join(lines) + "\n\n"


def monitors_lua(entries) -> str:
    """`entries` is a list of dicts: output, mode, position, scale."""
    body = _header(
        "Display layout. Change it in starch-config, or with nwg-displays.",
        """
Scale must land on a whole pixel: RESOLUTION / SCALE has to be an integer in
both axes, and the scale itself a multiple of 1/120. Hyprland does not error
on a bad value, it silently snaps to the nearest legal one — which is why
starch-config only offers scales that are legal for the mode in question.
        """,
    )

    for e in entries:
        body += (
            'hl.monitor({{ output = "{output}", mode = "{mode}", '
            'position = "{position}", scale = {scale} }})\n'
        ).format(**e)

    fallback = entries[0]["scale"] if entries else 1
    body += (
        "\n-- Catch-all for a display plugged in later. If its resolution does not\n"
        "-- divide evenly by this scale Hyprland will snap to the nearest legal one;\n"
        "-- run starch-config again to give it a line of its own.\n"
        f'hl.monitor({{ output = "", mode = "preferred", position = "auto", scale = {fallback} }})\n'
    )
    return body


def scale_str(scale: float) -> str:
    """Hyprland wants enough digits that 4/3 does not read as 1.33."""
    text = f"{scale:.7f}".rstrip("0").rstrip(".")
    return text or "1"


# ── hypridle ─────────────────────────────────────────────────────────────────
# Timeouts are seconds; None means "never", and that listener is left out.


def hypridle_conf(dim, blank, lock, suspend) -> str:
    """Render hypridle.conf from four timeouts.

    Written whole rather than patched, because the listeners have to come out
    in ascending order of timeout to read sensibly, and turning one off means
    removing its block rather than blanking a number.
    """
    lines = [
        "#" * 80,
        "#  hypridle — idle management",
        "#",
        f"#  {BANNER}. Edits here are overwritten.",
        "#",
        "#  The hyprctl calls are Lua. With a Lua config Hyprland evaluates",
        "#  everything after `dispatch` as Lua, so the old `dispatch dpms off`",
        "#  is a syntax error that fails without a word.",
        "#" * 80,
        "",
        "general {",
        "    lock_cmd       = pidof hyprlock || hyprlock",
        "    before_sleep_cmd = loginctl lock-session",
        "    after_sleep_cmd  = hyprctl dispatch 'hl.dsp.dpms({ action = \"on\" })'",
        "    ignore_dbus_inhibit = false",
        "}",
        "",
    ]

    listeners = []
    if dim:
        listeners.append(
            (dim, "brightnessctl -s set 10", "brightnessctl -r", "dim the backlight")
        )
    if blank:
        listeners.append(
            (
                blank,
                "hyprctl dispatch 'hl.dsp.dpms({ action = \"off\" })'",
                "hyprctl dispatch 'hl.dsp.dpms({ action = \"on\" })'",
                "displays off",
            )
        )
    if lock:
        listeners.append((lock, "loginctl lock-session", None, "lock"))
    if suspend:
        listeners.append((suspend, "systemctl suspend", None, "suspend"))

    for timeout, on_timeout, on_resume, what in sorted(listeners):
        lines.append(f"# {_minutes(timeout)} — {what}.")
        lines.append("listener {")
        lines.append(f"    timeout = {timeout}")
        lines.append(f"    on-timeout = {on_timeout}")
        if on_resume:
            lines.append(f"    on-resume  = {on_resume}")
        lines.append("}")
        lines.append("")

    if not listeners:
        lines.append("# Every timeout is off, so there are no listeners at all.")
        lines.append("")

    return "\n".join(lines)


def _minutes(seconds: int) -> str:
    if seconds % 60:
        return f"{seconds} seconds"
    m = seconds // 60
    return "1 minute" if m == 1 else f"{m} minutes"


# ── the Lua override module ──────────────────────────────────────────────────


def settings_lua(config: dict) -> str:
    """A generated Lua module that overrides a subset of the hand-written ones.

    hl.config sets one key at a time and leaves its siblings alone, which is
    what makes this safe: emitting input.repeat_rate here does not disturb the
    twenty other input settings in input.lua.
    """
    body = _header(
        "Settings changed in starch-config.",
        "The hand-written modules are the defaults. This file overrides only\n"
        "the handful you have changed, and hyprland.lua loads it last so it\n"
        "wins. Delete it to go back to the defaults.",
    )
    if not config:
        return body + "-- Nothing overridden.\n"
    return body + "hl.config(" + _lua_table(config, 0) + ")\n"


def _lua_table(value, depth: int) -> str:
    pad, inner = "    " * depth, "    " * (depth + 1)
    parts = []
    for key, item in value.items():
        if isinstance(item, dict):
            rendered = _lua_table(item, depth + 1)
        elif isinstance(item, bool):
            rendered = "true" if item else "false"
        elif isinstance(item, (int, float)):
            rendered = str(item)
        else:
            rendered = '"%s"' % str(item).replace('"', '\\"')
        parts.append(f"{inner}{key} = {rendered},")
    return "{\n" + "\n".join(parts) + f"\n{pad}}}"
