#!/usr/bin/env bash
# Colour theme picker — SUPER + SHIFT + T. Uses wofi so it matches the launcher.
#
#     theme.sh                  open the picker
#     theme.sh --set <slug>     apply a theme by filename, e.g. nord
#     theme.sh --list           slug and display name, one per line
#     theme.sh --current        slug of the theme in effect
#     theme.sh --no-reload      skip signalling the running apps (install time)
#
# A theme is 19 colour roles in ~/.config/hypr/themes/<slug>.theme. Applying one
# renders those roles into whatever form each app understands:
#
#   hypr/colors.conf    $role = rgb(hex)     sourced by theme.conf
#   waybar/colors.css   @define-color        imported by style.css
#   wofi/colors.css     @define-color        imported by style.css
#   kitty/colors.conf   name #hex            included by kitty.conf
#   mako/colors         key=#hex + sections  included by mako/config
#
# hyprlock.conf and waybar/config.jsonc are patched in place instead. hyprlock
# is deliberately not switched to an include: a mistake there locks you out of
# the session, and there is no way to dry-run its config. waybar's calendar
# colours live inside JSON format strings, which cannot reference a CSS name.
set -euo pipefail

THEME_DIR="${THEME_DIR:-$HOME/.config/hypr/themes}"
CFG="${XDG_CONFIG_HOME:-$HOME/.config}"
ACTIVE_FILE="$CFG/hypr/.active-theme"
RELOAD=1

note() { command -v notify-send >/dev/null && notify-send -a Theme "$@" || true; }

die() {
    printf 'theme.sh: %s\n' "$1" >&2
    note "Theme" "$1"
    exit 1
}

declare -A C=()

# `key = value`, ignoring comments and blanks. Values are bare six-digit hex so
# each renderer can prefix them the way its own format wants.
load_theme() {
    local file="$1" key val
    [[ -f $file ]] || die "no such theme: $file"
    C=()
    while IFS= read -r line; do
        line="${line%%#*}"
        [[ $line == *=* ]] || continue
        key="${line%%=*}"; val="${line#*=}"
        key="${key//[[:space:]]/}"; val="${val//[[:space:]]/}"
        [[ -n $key && -n $val ]] && C["$key"]="$val"
    done < "$file"
    local role
    for role in crust mantle base surface0 surface1 overlay subtext text \
                rosewater red peach yellow green teal sapphire blue \
                lavender mauve pink; do
        [[ -n ${C[$role]:-} ]] || die "$file is missing the '$role' colour"
    done
}

# Write to a temp file in the same directory and move it into place, so a
# failure part-way through cannot leave an app reading half a config.
emit() {
    local dest="$1" tmp
    mkdir -p "${dest%/*}"
    tmp="$(mktemp "${dest}.XXXXXX")"
    cat > "$tmp"
    chmod 644 "$tmp"
    mv "$tmp" "$dest"
}

render_hypr() {
    {
        echo "# Generated by theme.sh — edits here are overwritten."
        echo "# Active theme: ${C[name]:-unknown}"
        echo
        local role
        for role in crust mantle base surface0 surface1 overlay subtext text \
                    rosewater red peach yellow green teal sapphire blue \
                    lavender mauve pink; do
            printf '$%-9s = rgb(%s)\n' "$role" "${C[$role]}"
        done
        echo
        echo "# theme.conf used \$surface before the palette was split out."
        printf '$%-9s = rgb(%s)\n' "surface" "${C[surface0]}"
    } | emit "$CFG/hypr/colors.conf"
}

render_gtk_css() {
    local dest="$1"
    {
        echo "/* Generated by theme.sh — edits here are overwritten."
        echo "   Active theme: ${C[name]:-unknown} */"
        local role
        for role in crust mantle base surface0 surface1 overlay subtext text \
                    rosewater red peach yellow green teal sapphire blue \
                    lavender mauve pink; do
            printf '@define-color %-9s #%s;\n' "$role" "${C[$role]}"
        done
    } | emit "$dest"
}

render_kitty() {
    {
        echo "# Generated by theme.sh — edits here are overwritten."
        echo "# Active theme: ${C[name]:-unknown}"
        echo
        echo "foreground            #${C[text]}"
        echo "background            #${C[base]}"
        echo "selection_foreground  #${C[base]}"
        echo "selection_background  #${C[rosewater]}"
        echo
        echo "cursor                #${C[rosewater]}"
        echo "cursor_text_color     #${C[base]}"
        echo
        echo "url_color             #${C[rosewater]}"
        echo "active_border_color   #${C[lavender]}"
        echo "inactive_border_color #${C[overlay]}"
        echo "bell_border_color     #${C[yellow]}"
        echo
        echo "active_tab_foreground   #${C[crust]}"
        echo "active_tab_background   #${C[mauve]}"
        echo "inactive_tab_foreground #${C[text]}"
        echo "inactive_tab_background #${C[mantle]}"
        echo "tab_bar_background      #${C[crust]}"
        echo
        echo "# black"
        echo "color0  #${C[surface1]}"
        echo "color8  #${C[overlay]}"
        echo "# red"
        echo "color1  #${C[red]}"
        echo "color9  #${C[red]}"
        echo "# green"
        echo "color2  #${C[green]}"
        echo "color10 #${C[green]}"
        echo "# yellow"
        echo "color3  #${C[yellow]}"
        echo "color11 #${C[yellow]}"
        echo "# blue"
        echo "color4  #${C[blue]}"
        echo "color12 #${C[blue]}"
        echo "# magenta"
        echo "color5  #${C[pink]}"
        echo "color13 #${C[pink]}"
        echo "# cyan"
        echo "color6  #${C[teal]}"
        echo "color14 #${C[teal]}"
        echo "# white"
        echo "color7  #${C[subtext]}"
        echo "color15 #${C[text]}"
    } | emit "$CFG/kitty/colors.conf"
}

# mako has no variables, so the colours and every section that sets one live
# here. config includes this before declaring any section of its own.
render_mako() {
    {
        echo "# Generated by theme.sh — edits here are overwritten."
        echo "# Active theme: ${C[name]:-unknown}"
        echo
        echo "background-color=#${C[base]}e6"
        echo "text-color=#${C[text]}"
        echo "border-color=#${C[mauve]}"
        echo "progress-color=over #${C[surface1]}"
        echo
        echo "[urgency=low]"
        echo "border-color=#${C[surface1]}"
        echo "text-color=#${C[subtext]}"
        echo "default-timeout=4000"
        echo
        echo "[urgency=normal]"
        echo "border-color=#${C[mauve]}"
        echo
        echo "[urgency=critical]"
        echo "border-color=#${C[red]}"
        echo "background-color=#${C[base]}f2"
        echo "text-color=#${C[red]}"
        echo "# Critical notifications stay until dismissed."
        echo "default-timeout=0"
    } | emit "$CFG/mako/colors"
}

# hyprlock keeps its palette inline. Replace the value of each `$name = rgb(..)`
# line and the two hex literals inside the pango markup, leaving all else alone.
patch_hyprlock() {
    local conf="$CFG/hypr/hyprlock.conf" tmp
    [[ -w $conf ]] || return 0
    tmp="$(mktemp "${conf}.XXXXXX")"
    awk -v c_base="${C[base]}"       -v c_text="${C[text]}" \
        -v c_mauve="${C[mauve]}"     -v c_red="${C[red]}" \
        -v c_surface="${C[surface0]}" -v c_subtext="${C[subtext]}" '
        function setvar(n, v) { return sprintf("$%-7s = rgb(%s)", n, v) }
        /^[[:space:]]*\$base[[:space:]]*=/    { print setvar("base",    c_base);    next }
        /^[[:space:]]*\$text[[:space:]]*=/    { print setvar("text",    c_text);    next }
        /^[[:space:]]*\$mauve[[:space:]]*=/   { print setvar("mauve",   c_mauve);   next }
        /^[[:space:]]*\$red[[:space:]]*=/     { print setvar("red",     c_red);     next }
        /^[[:space:]]*\$surface[[:space:]]*=/ { print setvar("surface", c_surface); next }
        # Pango markup inside hyprlang escapes "#" as "##".
        /placeholder_text/ { sub(/##[0-9a-fA-F]{6}/, "##" c_subtext); print; next }
        /fail_text/        { sub(/##[0-9a-fA-F]{6}/, "##" c_red);     print; next }
        { print }
    ' "$conf" > "$tmp" && chmod 644 "$tmp" && mv "$tmp" "$conf" || rm -f "$tmp"
}

# waybar's calendar colours sit inside JSON format strings, where a CSS name
# means nothing — the hex has to be substituted directly.
patch_waybar_json() {
    local conf="$CFG/waybar/config.jsonc" tmp
    [[ -w $conf ]] || return 0
    tmp="$(mktemp "${conf}.XXXXXX")"
    awk -v months="${C[mauve]}"   -v days="${C[text]}"  -v weeks="${C[sapphire]}" \
        -v weekdays="${C[peach]}" -v today="${C[red]}" '
        function recolor(c) { sub(/#[0-9a-fA-F]{6}/, "#" c); }
        /"months"/   { recolor(months)   } 
        /"days"/     { recolor(days)     }
        /"weeks"/    { recolor(weeks)    }
        /"weekdays"/ { recolor(weekdays) }
        /"today"/    { recolor(today)    }
        { print }
    ' "$conf" > "$tmp" && chmod 644 "$tmp" && mv "$tmp" "$conf" || rm -f "$tmp"
}

reload_apps() {
    [[ $RELOAD -eq 1 ]] || return 0
    hyprctl reload >/dev/null 2>&1 || true
    pkill -SIGUSR2 -x waybar 2>/dev/null || true
    makoctl reload >/dev/null 2>&1 || true
    # kitty reloads its config on SIGUSR1, in every running instance.
    pkill -SIGUSR1 -x kitty 2>/dev/null || true
}

apply() {
    local slug="$1"
    load_theme "$THEME_DIR/$slug.theme"
    render_hypr
    render_gtk_css "$CFG/waybar/colors.css"
    render_gtk_css "$CFG/wofi/colors.css"
    render_kitty
    render_mako
    patch_hyprlock
    patch_waybar_json
    printf '%s\n' "$slug" > "$ACTIVE_FILE"
    reload_apps
    [[ $RELOAD -eq 1 ]] && note "Theme" "${C[name]:-$slug}"
    return 0
}

list_themes() {
    local f slug name
    [[ -d $THEME_DIR ]] || die "no theme directory: $THEME_DIR"
    shopt -s nullglob
    for f in "$THEME_DIR"/*.theme; do
        slug="${f##*/}"; slug="${slug%.theme}"
        name="$(sed -n 's/^[[:space:]]*name[[:space:]]*=[[:space:]]*//p' "$f" | head -1)"
        printf '%s\t%s\n' "$slug" "${name:-$slug}"
    done
    shopt -u nullglob
}

# --no-reload can precede any other argument.
if [[ ${1:-} == --no-reload ]]; then RELOAD=0; shift; fi

case "${1:-}" in
    --list)    list_themes ;;
    --current) cat "$ACTIVE_FILE" 2>/dev/null || echo "unknown" ;;
    --set)
        [[ -n ${2:-} ]] || die "--set needs a theme slug (try --list)"
        apply "$2"
        ;;
    "")
        mapfile -t rows < <(list_themes)
        [[ ${#rows[@]} -gt 0 ]] || die "no themes in $THEME_DIR"
        current="$(cat "$ACTIVE_FILE" 2>/dev/null || true)"
        # Display names go to wofi; the slug is recovered by position, so a
        # name containing anything at all is safe.
        choice="$(printf '%s\n' "${rows[@]#*$'\t'}" \
            | wofi --dmenu --prompt "Theme${current:+ (${current})}" \
                   --width 420 --height 400 --cache-file /dev/null --insensitive)" || exit 0
        [[ -n $choice ]] || exit 0
        for row in "${rows[@]}"; do
            if [[ ${row#*$'\t'} == "$choice" ]]; then apply "${row%%$'\t'*}"; exit 0; fi
        done
        die "no theme named $choice"
        ;;
    *) die "unknown option: $1 (try --list)" ;;
esac
