#!/usr/bin/env bash
# Colour theme picker — SUPER + SHIFT + T. Uses wofi so it matches the launcher.
#
#     theme.sh                  open the picker
#     theme.sh --set <slug>     apply a theme by filename, e.g. nord
#     theme.sh --list           slug and display name, one per line
#     theme.sh --current        slug of the theme in effect
#     theme.sh --no-reload      skip signalling the running apps (install time)
#
# A theme is 19 colour roles in ~/.config/hypr/themes/<slug>.theme, plus a
# twentieth, `accent`, derived from them: see load_theme. Applying one
# renders those roles into whatever form each app understands:
#
#   hypr/colors.lua     role = "hex" table   required by theme.lua
#   waybar/colors.css   @define-color        imported by style.css
#   kitty/colors.conf   name #hex            included by kitty.conf
#   mako/colors         key=#hex + sections  included by mako/config
#
# Three configs are patched in place instead of getting their own file:
#
#   wofi/style.css       wofi hands GTK the stylesheet as a string rather than
#                        a path, so a relative @import resolves against the
#                        working directory the launcher was started from. The
#                        colours are written between markers in style.css.
#   hyprlock.conf        deliberately not on an include: a mistake there locks
#                        you out, and there is no way to dry-run its config.
#   waybar/config.jsonc  the calendar colours live inside JSON format strings,
#                        which cannot reference a CSS name.
set -euo pipefail

CFG="${XDG_CONFIG_HOME:-$HOME/.config}"
THEME_DIR="${THEME_DIR:-$CFG/hypr/themes}"
ACTIVE_FILE="$CFG/hypr/.active-theme"
RELOAD=1

# Sentinels around the generated block in wofi/style.css. Matched by grep and
# sed, so keep them free of regex metacharacters.
WOFI_MARK_BEGIN="theme colours begin"
WOFI_MARK_END="theme colours end"

note() { command -v notify-send >/dev/null && notify-send -a Theme "$@" || true; }

die() {
    printf 'theme.sh: %s\n' "$1" >&2
    note "Theme" "$1"
    exit 1
}

declare -A C=()

# `key = value`, ignoring comments and blanks. Values are bare six-digit hex so
# each renderer can prefix them the way its own format wants.
load_theme() {
    local file="$1" key val
    [[ -f $file ]] || die "no such theme: $file"
    C=()
    while IFS= read -r line; do
        line="${line%%#*}"
        [[ $line == *=* ]] || continue
        key="${line%%=*}"; val="${line#*=}"
        key="${key//[[:space:]]/}"
        # Trim the ends only. Stripping every space would turn a display name
        # like "Catppuccin Mocha" into "CatppuccinMocha".
        val="${val#"${val%%[![:space:]]*}"}"
        val="${val%"${val##*[![:space:]]}"}"
        [[ -n $key && -n $val ]] && C["$key"]="$val"
    done < "$file"
    local role
    for role in crust mantle base surface0 surface1 overlay subtext text \
                rosewater red peach yellow green teal sapphire blue \
                lavender mauve pink; do
        [[ -n ${C[$role]:-} ]] || die "$file is missing the '$role' colour"
    done

    # The accent is the one colour the desktop uses to mean "this one": the
    # focused border, the active workspace, the selected row, the switch that
    # is on. It was mauve, hardcoded in a dozen files, which made changing it a
    # dozen edits. Now it is a role like any other.
    #
    # A theme may name its own by setting `accent = <hex>` or `accent = teal`;
    # anything that is not six hex digits is read as the name of another role.
    #
    # Without one it is mauve, which is what every one of these files was
    # hardcoded to before this role existed, and — for the Catppuccin themes
    # that most of these follow — what upstream calls the accent. Defaulting to
    # anything else does not restyle the desktop, it redefines the theme: pick
    # sapphire here and Catppuccin Mocha stops looking like Catppuccin Mocha,
    # and Nord and Gruvbox change with it.
    local want="${C[accent]:-mauve}"
    if [[ $want =~ ^[0-9a-fA-F]{6}$ ]]; then
        C[accent]="$want"
    else
        [[ -n ${C[$want]:-} ]] || die "$file: accent names '$want', which is not a colour here"
        C[accent]="${C[$want]}"
    fi
}

# Write to a temp file in the same directory and move it into place, so a
# failure part-way through cannot leave an app reading half a config.
emit() {
    local dest="$1" tmp
    mkdir -p "${dest%/*}"
    tmp="$(mktemp "${dest}.XXXXXX")"
    cat > "$tmp"
    chmod 644 "$tmp"
    mv "$tmp" "$dest"
}

# Hyprland's config is Lua as of 0.55 (.conf is removed in 0.57), so the
# palette is a module returning a table. theme.lua does `require("colors")`
# and wraps each value in rgb(...) itself.
render_hypr() {
    {
        echo "-- Generated by theme.sh — edits here are overwritten."
        echo "-- Active theme: ${C[name]:-unknown}"
        echo "return {"
        local role
        for role in crust mantle base surface0 surface1 overlay subtext text \
                    rosewater red peach yellow green teal sapphire blue \
                    lavender mauve pink accent; do
            printf '    %-9s = "%s",\n' "$role" "${C[$role]}"
        done
        echo "}"
    } | emit "$CFG/hypr/colors.lua"
}

define_colors() {
    local role
    for role in crust mantle base surface0 surface1 overlay subtext text \
                rosewater red peach yellow green teal sapphire blue \
                lavender mauve pink accent; do
        printf '@define-color %-9s #%s;\n' "$role" "${C[$role]}"
    done
}

# Waybar loads style.css with a path, so a relative @import resolves against
# the stylesheet and a separate colours file works.
render_gtk_css() {
    local dest="$1"
    {
        echo "/* Generated by theme.sh — edits here are overwritten."
        echo "   Active theme: ${C[name]:-unknown} */"
        define_colors
    } | emit "$dest"
}

# wofi does not: it hands GTK the stylesheet as a string, so GTK has no idea
# where the file lives and resolves a relative @import against the current
# working directory — which is wherever the launcher happened to be started
# from. The colours are written into style.css between markers instead.
patch_wofi_css() {
    local conf="$CFG/wofi/style.css" tmp
    [[ -w $conf ]] || return 0
    if ! grep -q "$WOFI_MARK_BEGIN" "$conf" || ! grep -q "$WOFI_MARK_END" "$conf"; then
        printf 'theme.sh: %s has no theme markers; wofi keeps its current colours\n' \
            "$conf" >&2
        return 0
    fi
    tmp="$(mktemp "${conf}.XXXXXX")" || return 0
    {
        sed "/$WOFI_MARK_BEGIN/q" "$conf"
        define_colors
        sed -n "/$WOFI_MARK_END/,\$p" "$conf"
    } > "$tmp" && chmod 644 "$tmp" && mv "$tmp" "$conf" || rm -f "$tmp"
}

render_kitty() {
    {
        echo "# Generated by theme.sh — edits here are overwritten."
        echo "# Active theme: ${C[name]:-unknown}"
        echo
        echo "foreground            #${C[text]}"
        echo "background            #${C[base]}"
        echo "selection_foreground  #${C[base]}"
        echo "selection_background  #${C[rosewater]}"
        echo
        echo "cursor                #${C[rosewater]}"
        echo "cursor_text_color     #${C[base]}"
        echo
        echo "url_color             #${C[rosewater]}"
        echo "active_border_color   #${C[lavender]}"
        echo "inactive_border_color #${C[overlay]}"
        echo "bell_border_color     #${C[yellow]}"
        echo
        echo "active_tab_foreground   #${C[crust]}"
        echo "active_tab_background   #${C[accent]}"
        echo "inactive_tab_foreground #${C[text]}"
        echo "inactive_tab_background #${C[mantle]}"
        echo "tab_bar_background      #${C[crust]}"
        echo
        echo "# black"
        echo "color0  #${C[surface1]}"
        echo "color8  #${C[overlay]}"
        echo "# red"
        echo "color1  #${C[red]}"
        echo "color9  #${C[red]}"
        echo "# green"
        echo "color2  #${C[green]}"
        echo "color10 #${C[green]}"
        echo "# yellow"
        echo "color3  #${C[yellow]}"
        echo "color11 #${C[yellow]}"
        echo "# blue"
        echo "color4  #${C[blue]}"
        echo "color12 #${C[blue]}"
        echo "# magenta"
        echo "color5  #${C[pink]}"
        echo "color13 #${C[pink]}"
        echo "# cyan"
        echo "color6  #${C[teal]}"
        echo "color14 #${C[teal]}"
        echo "# white"
        echo "color7  #${C[subtext]}"
        echo "color15 #${C[text]}"
    } | emit "$CFG/kitty/colors.conf"
}

# mako has no variables, so the colours and every section that sets one live
# here. config includes this before declaring any section of its own.
render_mako() {
    {
        echo "# Generated by theme.sh — edits here are overwritten."
        echo "# Active theme: ${C[name]:-unknown}"
        echo
        echo "background-color=#${C[base]}e6"
        echo "text-color=#${C[text]}"
        echo "border-color=#${C[accent]}"
        echo "progress-color=over #${C[surface1]}"
        echo
        echo "[urgency=low]"
        echo "border-color=#${C[surface1]}"
        echo "text-color=#${C[subtext]}"
        echo "default-timeout=4000"
        echo
        echo "[urgency=normal]"
        echo "border-color=#${C[accent]}"
        echo
        echo "[urgency=critical]"
        echo "border-color=#${C[red]}"
        echo "background-color=#${C[base]}f2"
        echo "text-color=#${C[red]}"
        echo "# Critical notifications stay until dismissed."
        echo "default-timeout=0"
    } | emit "$CFG/mako/colors"
}

# hyprlock keeps its palette inline. Replace the value of each `$name = rgb(..)`
# line and the two hex literals inside the pango markup, leaving all else alone.
patch_hyprlock() {
    local conf="$CFG/hypr/hyprlock.conf" tmp
    [[ -w $conf ]] || return 0
    tmp="$(mktemp "${conf}.XXXXXX")"
    awk -v c_base="${C[base]}"       -v c_text="${C[text]}" \
        -v c_accent="${C[accent]}"   -v c_red="${C[red]}" \
        -v c_surface="${C[surface0]}" -v c_subtext="${C[subtext]}" '
        function setvar(n, v) { return sprintf("$%-7s = rgb(%s)", n, v) }
        /^[[:space:]]*\$base[[:space:]]*=/    { print setvar("base",    c_base);    next }
        /^[[:space:]]*\$text[[:space:]]*=/    { print setvar("text",    c_text);    next }
        /^[[:space:]]*\$accent[[:space:]]*=/  { print setvar("accent",  c_accent);  next }
        /^[[:space:]]*\$red[[:space:]]*=/     { print setvar("red",     c_red);     next }
        /^[[:space:]]*\$surface[[:space:]]*=/ { print setvar("surface", c_surface); next }
        # Pango markup inside hyprlang escapes "#" as "##".
        /placeholder_text/ { sub(/##[0-9a-fA-F]{6}/, "##" c_subtext); print; next }
        /fail_text/        { sub(/##[0-9a-fA-F]{6}/, "##" c_red);     print; next }
        { print }
    ' "$conf" > "$tmp" && chmod 644 "$tmp" && mv "$tmp" "$conf" || rm -f "$tmp"
}

# waybar's calendar colours sit inside JSON format strings, where a CSS name
# means nothing — the hex has to be substituted directly.
patch_waybar_json() {
    local conf="$CFG/waybar/config.jsonc" tmp
    [[ -w $conf ]] || return 0
    tmp="$(mktemp "${conf}.XXXXXX")"
    awk -v months="${C[accent]}"   -v days="${C[text]}"  -v weeks="${C[sapphire]}" \
        -v weekdays="${C[peach]}" -v today="${C[red]}" '
        function recolor(c) { sub(/#[0-9a-fA-F]{6}/, "#" c); }
        /"months"/   { recolor(months)   } 
        /"days"/     { recolor(days)     }
        /"weeks"/    { recolor(weeks)    }
        /"weekdays"/ { recolor(weekdays) }
        /"today"/    { recolor(today)    }
        { print }
    ' "$conf" > "$tmp" && chmod 644 "$tmp" && mv "$tmp" "$conf" || rm -f "$tmp"
}

reload_apps() {
    [[ $RELOAD -eq 1 ]] || return 0
    hyprctl reload >/dev/null 2>&1 || true
    pkill -SIGUSR2 -x waybar 2>/dev/null || true
    makoctl reload >/dev/null 2>&1 || true
    # kitty reloads its config on SIGUSR1, in every running instance.
    pkill -SIGUSR1 -x kitty 2>/dev/null || true
}

apply() {
    local slug="$1"
    load_theme "$THEME_DIR/$slug.theme"
    render_hypr
    render_gtk_css "$CFG/waybar/colors.css"
    patch_wofi_css
    render_kitty
    render_mako
    patch_hyprlock
    patch_waybar_json
    printf '%s\n' "$slug" > "$ACTIVE_FILE"
    reload_apps
    [[ $RELOAD -eq 1 ]] && note "Theme" "${C[name]:-$slug}"
    return 0
}

list_themes() {
    local f slug name
    [[ -d $THEME_DIR ]] || die "no theme directory: $THEME_DIR"
    shopt -s nullglob
    for f in "$THEME_DIR"/*.theme; do
        slug="${f##*/}"; slug="${slug%.theme}"
        name="$(sed -n 's/^[[:space:]]*name[[:space:]]*=[[:space:]]*//p' "$f" | head -1)"
        printf '%s\t%s\n' "$slug" "${name:-$slug}"
    done
    shopt -u nullglob
}

# --no-reload can precede any other argument.
if [[ ${1:-} == --no-reload ]]; then RELOAD=0; shift; fi

case "${1:-}" in
    --list)    list_themes ;;
    --current) cat "$ACTIVE_FILE" 2>/dev/null || echo "unknown" ;;
    --set)
        [[ -n ${2:-} ]] || die "--set needs a theme slug (try --list)"
        apply "$2"
        ;;
    "")
        mapfile -t rows < <(list_themes)
        [[ ${#rows[@]} -gt 0 ]] || die "no themes in $THEME_DIR"
        current="$(cat "$ACTIVE_FILE" 2>/dev/null || true)"
        # Display names go to wofi; the slug is recovered by position, so a
        # name containing anything at all is safe.
        choice="$(printf '%s\n' "${rows[@]#*$'\t'}" \
            | wofi --dmenu --prompt "Theme${current:+ (${current})}" \
                   --width 420 --height 400 --cache-file /dev/null --insensitive)" || exit 0
        [[ -n $choice ]] || exit 0
        for row in "${rows[@]}"; do
            if [[ ${row#*$'\t'} == "$choice" ]]; then apply "${row%%$'\t'*}"; exit 0; fi
        done
        die "no theme named $choice"
        ;;
    *) die "unknown option: $1 (try --list)" ;;
esac
